# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AHS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AHS

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'

  target 'AHSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AHSUITests' do
    # Pods for testing
  end

end
