name: AHS
targets:
    AHS:
        type: application
        platform: iOS
        deploymentTarget: 15.0
        sources: [AHS]
        settings:
            PRODUCT_BUNDLE_IDENTIFIER: com.ArcadiaApaches.ArcadiaHighSchoolApp
            TARGETED_DEVICE_FAMILY: 1
            CODE_SIGN_ENTITLEMENTS: AHS/AHS.entitlements
    AHSTests:
        type: bundle.unit-test
        platform: iOS
        sources: [AHSTests]
    AHSUITests:
        type: bundle.ui-testing
        platform: iOS
        sources: [AHSUITests]
